### ISSUE TITLE
Cannot build program

### ISSUE THREAD

**Issue by saulspatz** [shlomif/black-hole-solitaire#5]
I'm having trouble building the software, perhaps due to my pristine, unsullied ignorance of CMake.  I cloned the repo and made a folder black-hole-solitaire/black-hole-solitaire/c-solver/build.  Then

cd build
cmake-gui ..

I told it that the source was in c-solver and that the program should be built in build.  It gave a message, "Configuring incomplete, errors occurred, and the only thing I could see specifically was "Rinutils_DIR-NOTFOUND".  So, I configured Rinutils-DIR to be c-solver/rinutils, but I got the same error.    I looked in CMakeOutput.log, but I didn't see anything that looked like an error, but I'm attaching in it case I've overlooked something.
 
I'm using CMake version 3.16.3.  

Please give me any guidance you can.

[CMakeOutput.log](https://github.com/shlomif/black-hole-solitaire/files/9178861/CMakeOutput.log)

**Comment by shlomif** [comment]
@saulspatz : hi:

1. does it happen with the src tarball - https://www.shlomifish.org/open-source/projects/black-hole-solitaire-solver/#download ?

2. please provide more sys info, see https://github.com/shlomif/writing-the-perfect-question ,

3. Can you provide a docker script, gh actions config / etc?

**Comment by shlomif** [comment]
closing as it's been a month.
